# Generated by Django 6.1 on 2026-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=100)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=250)),
                ('duration', models.CharField(help_text='e.g. 2021 - 2025', max_length=100)),
                ('grade', models.CharField(blank=True, help_text='e.g. CGPA: 8.75 / 10.0', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('frontend', 'Frontend & JavaScript'), ('web', 'Web Applications'), ('database', 'Database & SQL Systems'), ('iot', 'IoT & Embedded Systems')], default='web', max_length=20)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated tech tags, e.g., JavaScript, HTML5, CSS3', max_length=300)),
                ('github_link', models.URLField(max_length=300)),
                ('live_demo_link', models.URLField(blank=True, max_length=300, null=True)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vignesh', max_length=100)),
                ('title', models.CharField(default='Final-Year ECE Engineer & Full-Stack Developer', max_length=200)),
                ('bio', models.TextField(default='Electronics & Communication Engineering student passionate about bridging robust hardware systems with modern full-stack web architectures and SQL databases.')),
                ('email', models.EmailField(default='vigneshvicky24092005@gmail.com', max_length=254)),
                ('github_url', models.URLField(default='https://github.com/vigneshvicky24092005-ai')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('location', models.CharField(default='India', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profiles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('software', 'Software & Web Development'), ('database', 'Database & SQL'), ('ece', 'ECE, Embedded & IoT'), ('tools', 'Tools & Workflow')], default='software', max_length=20)),
                ('proficiency', models.CharField(default='Proficient', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-code', help_text='FontAwesome class, e.g. fab fa-js', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
